# Generated by Django 5.1.4 on 2024-12-27 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_alter_folder_name_folder_unique_folder_name_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_folder_name_owner',
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('name', 'parent', 'owner'), name='unique_folder_name_owner'),
        ),
    ]
